export const dataEng: any = {
    "intro": {
        room: "",
        title: "Intro",
        mainTitle: "Intro",
        cover: "/img/room/Intro.jpeg",
        audio: "/audio/intro_EN.wav",
        key: "intro",
    },
    "room-1": {
        room: "Room 1",
        title: "Dan Les Rues",
        mainTitle: "Pre-Fall 2018 Dan Les Rues",
        subtitle: "Pre-Fall 2018",
        cover: "/img/room/danslesrues.jpg",
        audio: "/audio/Room1_Pre-Fall2018DanLesRues_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-1",
    },
    "room-2": {
        room: "Room 2",
        title: "Control Room",
        mainTitle: "Control Room",
        cover: "/img/room/controlroom.jpg",
        audio: "/audio/Room2_ControlRoom_EN.wav",
        artist: "",
        key: "room-2",
    },
    "room-3": {
        room: "Room 3",
        title: "Gucci Bloom",
        subtitle: "",
        mainTitle: "Gucci Bloom",
        cover: "/img/room/GucciBloom.jpg",
        audio: "/audio/Room3_GucciBloom_EN.wav",
        artist: "",
        key: "room-3",

    },
    "room-4": {
        room: "Room 4",
        title: "Rebellious Romantics",
        subtitle: "SS 2016",
        mainTitle: "SS 2016 Rebellious Romantics",
        cover: "/img/room/rebelliousromantics.jpg",
        audio: "/audio/Room4_SS2016RebelliousRomantics_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-4",
    },
    "room-5": {
        room: "Room 5",
        title: "Gucci Collectors",
        subtitle: "FW 2018 ",
        mainTitle: "FW 2018 Gucci Collectors",
        cover: "/img/room/Gucci_Collectors.jpg",
        audio: "/audio/Room5_FW2018GucciCollectors_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-5",
    },
    "room-6": {
        room: "Room 6",
        title: "Talk Show",
        subtitle: "Gucci Beloved",
        mainTitle: "Gucci Beloved Talk Show",
        cover: "/img/room/Talkshow.jpg",
        audio: "/audio/Room6_GucciBelovedTalkShow_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-6",
    },
    "room-7": {
        room: "Room 7",
        title: "The Dionysus Dance",
        subtitle: "Cruise 2016",
        mainTitle: "Cruise 2016 The Dionysus Dance",
        cover: "/img/room/Cruise_2015.jpg",
        audio: "/audio/Room7_Cruise2016TheDionysusDance_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-7",
    },
    "room-8": {
        room: "Room 8",
        title: "Urban Romanticism",
        subtitle: "FW 2015",
        mainTitle: "FW 2015 Urban Romanticism",
        cover: "/img/room/UrbanRomanticism.jpg",
        audio: "/audio/Room8_FW2015UrbanRomanticism_EN.wav",
        intro: "intro",
        artist: "",
        key: "room-8",
    },
}

export const dataChi: any = {
    "intro": {
        room: "",
        title: "介绍",
        mainTitle: "介绍",
        cover: "/img/room/Intro.jpeg",
        audio: "/audio/intro_CN.wav",
        key: "intro",
    },
    "room-1": {
        room: "房间 1",
        title: "五月风暴",
        mainTitle: "五月风暴",
        cover: "/img/room/danslesrues.jpg",
        audio: "/audio/房间1_五月风暴.wav",
        artist: "",
        key: "room-1",

    },
    "room-2": {
        room: "房间 2",
        title: "时空总控",
        mainTitle: "时空总控",
        cover: "/img/room/controlroom.jpg",
        audio: "/audio/房间2_时空总控.wav",
        artist: "",
        key: "room-2",

    },
    "room-3": {
        room: "房间 3",
        title: "花悦仙境",
        mainTitle: "花悦仙境",
        cover: "/img/room/GucciBloom.jpg",
        audio: "/audio/房间3_花悦仙境.wav",
        intro: "intro",
        artist: "",
        key: "room-3",
    },
    "room-4": {
        room: "房间 4",
        title: "叛逆心室",
        mainTitle: "叛逆心室",
        cover: "/img/room/rebelliousromantics.jpg",
        audio: "/audio/房间4_叛逆心室.wav",
        artist: "",
        key: "room-4",
    },
    "room-5": {
        room: "房间 5",
        title: "搜藏之家",
        mainTitle: "搜藏之家",
        cover: "/img/room/Gucci_Collectors.jpg",
        audio: "/audio/房间5_搜藏之家.wav",
        artist: "",
        key: "room-5",
    },
    "room-6": {
        room: "房间 6",
        title: "宠儿脱口秀",
        mainTitle: "宠儿脱口秀",
        cover: "/img/room/Talkshow.jpg",
        audio: "/audio/房间6_宠儿脱口秀.wav",
        artist: "",
        key: "room-6",
    },
    "room-7": {
        room: "房间 7",
        title: "酒神舞会",
        mainTitle: "酒神舞会",
        cover: "/img/room/Cruise_2015.jpg",
        audio: "/audio/房间7_酒神舞会.wav",
        artist: "",
        key: "room-7",
    },
    "room-8": {
        room: "房间 8",
        title: "都会漫游者",
        mainTitle: "都会漫游者",
        cover: "/img/room/UrbanRomanticism.jpg",
        audio: "/audio/房间8_都会漫游者.wav",
        artist: "",
        key: "room-8",
    }
}